plugins {
    id 'java'
}

group = 'com.godsdefense'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.dom4j:dom4j:2.1.4'
}

task run(type: JavaExec) {
    mainClass = 'AnyKey.Main'
    classpath = sourceSets.main.runtimeClasspath
}
